### ISSUE TITLE
Cookies separated by comma instead than semi-colon in embedded login page

### ISSUE THREAD

**Issue by michelemottini** [sparseware/ccp-bellavista#6]
When using a custom login the client hosts the login page of the target server. If this page sets multiple cookies they are returned to the server separated by `,` instead that by `;` - e.g:

![image](https://cloud.githubusercontent.com/assets/1046280/13508894/ef0eebf6-e156-11e5-9946-9d65ce6da2a8.png)

instead than

![image](https://cloud.githubusercontent.com/assets/1046280/13508849/b868a1d2-e156-11e5-8ce1-6398fa13bc37.png)

This cause the server not to 'see' the cookies after the first one, and the login process fails.

**Comment by sparseware** [comment]
This is an issue with the embedded WebBrowser and it's cookie handling.
This [StackOverFlow post]( http://stackoverflow.com/questions/11533867/set-cookie-header-with-multiple-cookies) seems the be referring to the same problem you are having (i.e. the problem is in the server-side framework). You could use you sniffer to see what the client actually receives.

**Comment by michelemottini** [comment]
I don't think it is that StackOverflow issue, the sniffer sees two separate `Set-Cookie` headers coming from the server:

![image](https://cloud.githubusercontent.com/assets/1046280/13512671/170c6c1a-e16a-11e5-911f-a39dcb416390.png)

**Comment by sparseware** [comment]
I will do some more research into it. In the mean time could you tell me what O/S and java version you are running

**Comment by michelemottini** [comment]
Oh yes, sorry, I forgot about that.. 

Running on Windows 10, Java: platform 1.8, product 1.8.0_73

**Comment by sparseware** [comment]
Ok, I looks like the browser calls the runtime's cookie manager so I made a fix that you can try to see if it works.
You can download a new jar [here](http://healthcare.sparseware.com/bellavista-desktop-0.9.51.jar).
The jar is signed can can be verified with the jarsigner tool that comes with the jdk.

Beware that this version is  hot of the presses and not well tested

**Comment by michelemottini** [comment]
Hooray! The login works, thanks.

There is a different issue though (...nothing is easy...) - right after the login it seems that this version of the client tries to access a practitioner with a fixed id (that does not exist):

```
HTTP Exception: Not Found (http://himss.careevolution.com/Reveal519x.Adapter1.WebClient/api/fhir/Practitioner/1234)

http://himss.careevolution.com/Reveal519x.Adapter1.WebClient/api/fhir/Practitioner/1234
404 Not Found
{"resourceType":"OperationOutcome","text":{"status":"generated","div":"<div xmlns='http://www.w3.org/1999/xhtml'>There is no Practitioner with id &#39;1234&#39;.</div>"},"issue":[{"severity":"error","details":{"text":"There is no Practitioner with id '1234'."}}]}
	at com.appnativa.rare.net.JavaURLConnection.connectAndCheckForError(JavaURLConnection.java:843)
	at com.appnativa.rare.net.JavaURLConnection.open(JavaURLConnection.java:359)
	at com.appnativa.rare.net.ActionLink.connect(ActionLink.java:2591)
	at com.appnativa.rare.net.ActionLink.closeOutputEx(ActionLink.java:2521)
	at com.appnativa.rare.net.ActionLink.closeOutput(ActionLink.java:2456)
	at com.appnativa.rare.net.ActionLink.getReader(ActionLink.java:1000)
	at com.appnativa.rare.net.ActionLink.getContentAsString(ActionLink.java:781)
	at com.sparseware.bellavista.external.fhir.FHIRServer$AuthHandler$1.compute(FHIRServer.java:1476)
	at com.appnativa.rare.CancelableWorker.run(CancelableWorker.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by sparseware** [comment]
I will fix that for testing purposes, however in practice the client would still generate and error because the server did not return a valid user id. Populating the 'id_token' in your response with a valid practitioner profile should fix this.

**Comment by michelemottini** [comment]
I see, thanks. 

We could populate 'id_token', but in our system users are never associated with a practitioner and can or cannot be associated with a patient, so we would still not be returning a FHIR resource reference inside the 'id_token'...

**Comment by sparseware** [comment]
I will research to see if there is a standard mechanism for providing the needed info all within the id_token. You should be able to use "Person" for your use-case. So the profile value in the id_token would have "Person/some-identifier' and you server would support the “Person" endpoint. 

PS. If you want to test with the iOS client let me know and I will send you a Apple TestFlight invite. The iOS version is the original 0.9.5 version but you should be able to log in with it as the cookie handling on iOS is handled by the O/S.

**Comment by sparseware** [comment]
Based on the OAuth2 standard there should be a protected /UserInfo endpoint on the server that returns information about the user.  This end point returns information about the user as defined by the OAuth2 standard. It is documented in section 2.3 [here](http://openid.net/specs/openid-connect-basic-1_0-28.html)

The information returned is up to the server so you can choose to provide real names or not.
The client will require that the 'sub' and 'name' field be populated.

I will update the client to use this endpoint if the id_token does not contain a profile value. Also, the id_token can contain other information (per the standard). I will add a server configuration option to allow specifying that the id_token contains the user information as it would be returned by the /UserInfo endpoint. The property will be oauth_id_token_user_info_key and its value will be the name of the key in the id_token that represents the user information.

**Comment by michelemottini** [comment]
Using `/UserInfo` would be great (from my point of view at least...), because we already support it - although we use `user_name` instead than `name`. Example of a UserInfo result:

```
{
  "sub": "d2c0823f-c9be-e511-8125-0a1bfcb5150f",
  "user_name": "CEAdmin",
  "roles": [
    "Admin",
    "Clerk",
    "Clinician",
    "Galileo",
    "GalileoAdmin",
    "NaryaReadContent",
    "NaryaWriteContent"
  ],
  "family_name": "Administrator",
  "given_name": "CareEvolution",
  "email": "donotreply@careevolution.com"
}
```

How would the client know the UserInfo endpoint URL though? It is not in the FHIR conformance. Another configuration parameter?
(ours is the same as the token endpoint with 'UserInfo' instead than `Token`)

> I will update the client to use this endpoint if the id_token does not contain a profile value

...or if there is no `id_token` and/or the OAuth scope does not contain `openid profile` ?

> I will add a server configuration option to allow specifying that the id_token contains the user information as it would be returned by the /UserInfo endpoint. 

Nice idea

**Comment by sparseware** [comment]
I am writing the code as we speak.
The userinfo should be at the same level as the token endpoint. I will check for it in the conformance statement and if not present assume that this is where it is.

Your ‘user_name’ field  is fine as ‘name' should be the user’s full name.
The client uses ‘sub’ as the user’s id.

**Comment by sparseware** [comment]
Ok, there is a standard mechanism for discovering the userinfo endpoint.
Your server should have an endpoint that looks like this:
`https://<your.server.com>/.well-known/openid-configuration`

The `<your.server.com>` part is the value of the "iss" field in the id_token
If the id_token doesn't specify a profile value then the client will find the user endpoint using the above scheme and then call the endpoint to get the info.

Test it out and let me know. The new version is [here]( http://healthcare.sparseware.com/bellavista-desktop-0.9.52.jar)

**Comment by michelemottini** [comment]
Thanks! I'll do the changes on our side and let you know

**Comment by michelemottini** [comment]
I did the changes but there is some kind of problem - the client crashes during the login sequence:

```
Null Pointer Exception

java.lang.NullPointerException
	at com.appnativa.util.json.JSONObject.getString(JSONObject.java:595)
	at com.sparseware.bellavista.external.fhir.FHIRServer$AuthHandler$1.compute(FHIRServer.java:1494)
	at com.appnativa.rare.CancelableWorker.run(CancelableWorker.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

The last call the server received was the token request, the return value is something like this:

```
{
  "token_type": "Bearer",
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjdfNi1vMlVzRFJpakFpbUhsdU5YZF9QenBYbyJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L1dlYkNsaWVudFRlc3QuQWRhcHRlcjEuV2ViQ2xpZW50LyIsImV4cCI6MTQ1NzQxMTk1NSwibmJmIjoxNDU3MzkwMzU1LCJqdGkiOiIwZTdiYWU1Yi05ZDdkLTQ1MDEtYTY4NC1hNGNlZGJhZDc3YmQiLCJzdWIiOiJiMzZkNmU2Mi1hNGNlLWU1MTEtODNkNy0yODE4NzhkNThiNjAiLCJ1c2VyX25hbWUiOiJDRUFkbWluIiwiY2xpZW50X2lkIjoiT0F1dGhUZXN0In0.hJoNOoLNZ-uNx_No1tgFO4osKMZC1tOcN7WS13ZnSrSplSpoO6rHTpsBIVBSuSqiMBiTkuADvwmqLJX12hSL-McUEajXWUIDAID2uTQN2TeWOkZTNsX37eH3UtTYxxMJwTmG6oZTTgJteEicfC_7LV6-hHH4NaKTehYhz9CPuxnEryd8PKGjfmhpHPeL7pfiH2guFiDPnfYsaAP0VGLCu7TFpxZ4LyTulvxVyKEEfieTptHtFzhSd10LkdtdQv_owNCPedIyP21nrA2eU0ZzbUinfuxs6eDu_hZaVT8vnZ-x5l0I4l4fcnIbFcnrrrzpgInGkiqEOaoksAicyvkClw",
  "refresh_token": "efc9f7c6f71c4be8a9b2f648219fe66f",
  "expires_in": 21600,
  "need_patient_banner": false,
  "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjdfNi1vMlVzRFJpakFpbUhsdU5YZF9QenBYbyJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L1dlYkNsaWVudFRlc3QuQWRhcHRlcjEuV2ViQ2xpZW50LyIsImV4cCI6MTQ1NzQxMTk1NSwibmJmIjoxNDU3MzkwMzU1LCJzdWIiOiJiMzZkNmU2Mi1hNGNlLWU1MTEtODNkNy0yODE4NzhkNThiNjAiLCJ1c2VyX25hbWUiOiJDRUFkbWluIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiQ0VBZG1pbiIsIm5hbWUiOiJDYXJlRXZvbHV0aW9uIEFkbWluaXN0cmF0b3IiLCJyb2xlcyI6WyJBZG1pbiIsIkNsZXJrIiwiQ2xpbmljaWFuIiwiTmFyeWFSZWFkQ29udGVudCIsIk5hcnlhV3JpdGVDb250ZW50Il0sImZhbWlseV9uYW1lIjoiQWRtaW5pc3RyYXRvciIsImdpdmVuX25hbWUiOiJDYXJlRXZvbHV0aW9uIiwibWlkZGxlX25hbWUiOiJNLiIsImVtYWlsIjoiZG9ub3RyZXBseUBjYXJlZXZvbHV0aW9uLmNvbSJ9.EtA-H6srCLQtwYQgO_fC6bPW-fKnCaErZMInYJxkbV0n1BPSRTkNKRITiRy9LEbnOsQnydpnx2kIv_j8kAzDVpEm2-X6SiTfqyz6TzlYPuFYoLnLXaFeEI5t_nZrxXxfzweQLjuQSIJN9quZ2PAxxPd5FEQOxA_Jw3I9lThBkYrztodLjYkINFfWCD_O3AVwa-w2CvBScUSzb7FKUhvIlyFpBf1H7KCD9IEgGJRdL_SRLMW4FEwzcmS5E_zcVymOcuXTKixLWW-MtSTRH-Nv9GJsZXmqvW58eRgkKec1PjZjMpRxRspGWczObLKATlcm6kWDwpfEyrgsb55ifTHQhA"
}
```

**Comment by sparseware** [comment]
Sorry, it was still expecting the profile string at that point

Test it out and let me know. The new version is [here](http://healthcare.sparseware.com/bellavista-desktop-0.9.53.jar)

**Comment by michelemottini** [comment]
Thanks, progress but still no cigar:

```
HTTP Exception: Unauthorized (http://localhost/WebClientTest.Adapter1.WebClient/api/OAuth2/userinfo)

http://localhost/WebClientTest.Adapter1.WebClient/api/OAuth2/userinfo
401 Unauthorized
{
  "Message": "You are not authorized to access this resource."
}
	at com.appnativa.rare.net.JavaURLConnection.connectAndCheckForError(JavaURLConnection.java:843)
	at com.appnativa.rare.net.JavaURLConnection.open(JavaURLConnection.java:359)
	at com.appnativa.rare.net.ActionLink.connect(ActionLink.java:2591)
	at com.appnativa.rare.net.ActionLink.closeOutputEx(ActionLink.java:2521)
	at com.appnativa.rare.net.ActionLink.closeOutput(ActionLink.java:2456)
	at com.appnativa.rare.net.ActionLink.getReader(ActionLink.java:1000)
	at com.appnativa.rare.net.ActionLink.getContentAsString(ActionLink.java:781)
	at com.sparseware.bellavista.external.fhir.FHIRServer$AuthHandler.resolveUserInfo(FHIRServer.java:1598)
	at com.sparseware.bellavista.external.fhir.FHIRServer$AuthHandler$1.compute(FHIRServer.java:1506)
	at com.appnativa.rare.CancelableWorker.run(CancelableWorker.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

...are you passing the bearer token when you call `userinfo` ?

**Comment by sparseware** [comment]
I was bypassing, One more try [here](http://healthcare.sparseware.com/bellavista-desktop-0.9.54.jar)

**Comment by michelemottini** [comment]
Great! It works now, thanks
